server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/share?useUnicode=true&characterEncoding=utf-8&userSSL=false&allowMultiQueries=true
    username: root
    password: ymx1205
    driver-class-name: com.mysql.cj.jdbc.Driver
