server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/share?useUnicode=true&characterEncoding=utf-8&userSSL=false&allowMultiQueries=true
    username: root
    password: ymx1205
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启服务发现
      routes:
        - id: user_route
          order: 1
          uri: lb://user-service # 路由匹配地址，从注册中心根据服务名称进行负载均衡路由
          predicates:
            - Path=/user/** # 路由匹配的路径
#            - Header=token, \d+
#            - Before=2025-03-21T23:59:59+08:00 # 路由匹配的请求时间
#            - After=2025-03-21T23:59:59+08:00
#            - Between=2025-03-21T08:00:00+08:00,2025-03-21T23:59:59+08:00
#            - JDK=17
          filters:
            - StripPrefix=1 # 去掉匹配路径的前缀
#            - InvalidParamete=token,-1
        - id: content_route
          order: 1
          uri: lb://content-service # 路由匹配地址，从注册中心根据服务名称进行负载均衡路由
          predicates:
            - Path=/content-service/** # 路由匹配的路径
            - Method=GET # 路由匹配的请求方式
          filters:
            - StripPrefix=1 # 去掉匹配路径的前缀
#            - InvalidParamete=token,-1
    sentinel:
      filter:
        enabled: true
      transport:
        port: 8719
        dashboard: localhost:8888
      scg:
        fallback:
          mode: response
          response-status: 500
          response-body: '{"code":500,"msg":"网关流量超量！"}'

