server:
  port: 8084

spring:
  application:
    name: ai-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
  ai:
    dashscope:
      api-key: sk-02145313c43845adbbcfacb1eb3159c1