spring:
  application:
    name: admin-service
  mail:
    host: smtp.qq.com
    username: 2715550284@qq.com
    password: cmnnhccxauwydegh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  boot:
    admin:
      notify:
        mail:
          enabled: true
          from: 2715550284@qq.com
          to: 2715550284@qq.com
          cc: 2715550284@qq.com
        dingtalk:
          enabled: true
          webhook-url: https://oapi.dingtalk.com/robot/send?access_token=fe0cafc3cbb912230e337b2a8c4362e8c473e64c87fbbf9b1bca9ddd262870f9
          secret: SECccee13070887f4bc9a86038cbb74472828d78da307ed28ffd54ee41450326ce8
          message: "?? #{instance.registration.name} - #{instance.id} ???!!"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"