server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share?useSSL=false&serverTimezone=UTC
rocketmq:
  name-server: 43.137.12.232:9876
  producer:
    group: ymx-p-group
  consumer:
    group: ymx-c-group